name = "perf-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_name = "perf.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-01"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
